name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up SSH agent and add private key for EC2 access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC_SSH_KEY }}

    # Deploy updated code to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ec2-user@ec2-3-110-218-232.ap-south-1.compute.amazonaws.com "bash -s" << 'COMMANDS'
          cd Jenkins-Test
          git pull origin master
          npm install
          pm2 reload nodejs-app || pm2 start index.js --name nodejs-app
        COMMANDS

    # Cleanup (not strictly needed when using ssh-agent)
    - name: Cleanup SSH Key
      run: rm -f ~/.ssh/id_rsa
