name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Save the private key to a file
    - name: Create SSH Key File
      run: |
        echo "${{ secrets.EC_SSH_KEY }}" > root.pem
        chmod 600 root.pem

    # Deploy updated code to EC2
    - name: Deploy to EC2
      run: |
        ssh -i root.pem -o StrictHostKeyChecking=no ec2-user@ec2-3-110-218-232.ap-south-1.compute.amazonaws.com "bash -s" << 'COMMANDS'
          cd Jenkins-Test
          git pull origin master
          npm install
          node index.js
        COMMANDS

    # Cleanup
    - name: Remove SSH Key File
      run: rm -f root.pem
